from __future__ import annotations

from pathlib import Path


SEED = 42

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

DATE_START = "2024-01-01"
DATE_END = "2025-12-31"

MONTH_SEASONALITY = {
    1: 1.04,
    2: 0.95,
    3: 0.97,
    4: 1.00,
    5: 1.02,
    6: 1.01,
    7: 0.98,
    8: 1.00,
    9: 1.03,
    10: 1.07,
    11: 1.15,
    12: 1.18,
}

YEAR_GROWTH = {
    2024: 1.00,
    2025: 1.09,
}

REGION_FACTORS = {
    "Southeast": 1.34,
    "South": 1.10,
    "Northeast": 0.92,
    "Midwest": 0.82,
    "North": 0.70,
}

REGION_PRICE_ADJ = {
    "Southeast": 1.03,
    "South": 1.02,
    "Northeast": 0.99,
    "Midwest": 1.00,
    "North": 1.04,
}

REGION_DISCOUNT_ADJ = {
    "Southeast": 0.014,
    "South": 0.009,
    "Northeast": 0.007,
    "Midwest": 0.005,
    "North": 0.002,
}

REGION_COST_ADJ = {
    "Southeast": 1.00,
    "South": 1.00,
    "Northeast": 1.01,
    "Midwest": 1.02,
    "North": 1.04,
}

REGION_CUSTOMER_WEIGHTS = {
    "Southeast": 0.35,
    "South": 0.22,
    "Northeast": 0.19,
    "Midwest": 0.14,
    "North": 0.10,
}

GEOGRAPHY = {
    "Southeast": [
        {"State": "SP", "City": "Sao Paulo"},
        {"State": "RJ", "City": "Rio de Janeiro"},
        {"State": "MG", "City": "Belo Horizonte"},
    ],
    "South": [
        {"State": "PR", "City": "Curitiba"},
        {"State": "RS", "City": "Porto Alegre"},
        {"State": "SC", "City": "Florianopolis"},
    ],
    "Northeast": [
        {"State": "BA", "City": "Salvador"},
        {"State": "PE", "City": "Recife"},
        {"State": "CE", "City": "Fortaleza"},
    ],
    "Midwest": [
        {"State": "DF", "City": "Brasilia"},
        {"State": "GO", "City": "Goiania"},
        {"State": "MT", "City": "Cuiaba"},
    ],
    "North": [
        {"State": "AM", "City": "Manaus"},
        {"State": "PA", "City": "Belem"},
        {"State": "TO", "City": "Palmas"},
    ],
}

CHANNELS = [
    {
        "Sales Channel": "Online",
        "Volume Weight": 0.34,
        "Discount Bias": 0.016,
        "Cost Bias": 1.000,
        "Return Bias": 0.014,
        "Lead Days": 2.2,
    },
    {
        "Sales Channel": "Retail Stores",
        "Volume Weight": 0.28,
        "Discount Bias": 0.010,
        "Cost Bias": 0.998,
        "Return Bias": 0.010,
        "Lead Days": 3.4,
    },
    {
        "Sales Channel": "Distributors",
        "Volume Weight": 0.20,
        "Discount Bias": 0.024,
        "Cost Bias": 1.005,
        "Return Bias": 0.006,
        "Lead Days": 5.0,
    },
    {
        "Sales Channel": "Direct Sales",
        "Volume Weight": 0.18,
        "Discount Bias": 0.007,
        "Cost Bias": 0.993,
        "Return Bias": 0.004,
        "Lead Days": 2.8,
    },
]

SEGMENTS = [
    {"Segment": "Consumer", "Weight": 0.43, "Discount Bias": 0.010},
    {"Segment": "Small Business", "Weight": 0.36, "Discount Bias": 0.006},
    {"Segment": "Enterprise", "Weight": 0.21, "Discount Bias": 0.014},
]

CHANNEL_SEGMENT_COMPATIBILITY = {
    "Online": {"Consumer": 1.35, "Small Business": 1.00, "Enterprise": 0.55},
    "Retail Stores": {"Consumer": 1.15, "Small Business": 1.00, "Enterprise": 0.70},
    "Distributors": {"Consumer": 0.50, "Small Business": 1.20, "Enterprise": 1.45},
    "Direct Sales": {"Consumer": 0.40, "Small Business": 1.05, "Enterprise": 1.60},
}

PRODUCTS = [
    {
        "Product ID": "P001",
        "Product Name": "ApexBook 13",
        "Category": "Technology",
        "Sub-Category": "Laptops",
        "Base Price": 1450,
        "Base Cost Ratio": 0.77,
        "Discount Sensitivity": 1.10,
        "Demand Weight": 0.90,
        "Quantity Base": 1.2,
        "Return Bias": 0.018,
    },
    {
        "Product ID": "P002",
        "Product Name": "ApexBook 15 Pro",
        "Category": "Technology",
        "Sub-Category": "Laptops",
        "Base Price": 1890,
        "Base Cost Ratio": 0.79,
        "Discount Sensitivity": 1.18,
        "Demand Weight": 0.72,
        "Quantity Base": 1.1,
        "Return Bias": 0.020,
    },
    {
        "Product ID": "P003",
        "Product Name": "VisionView 24",
        "Category": "Technology",
        "Sub-Category": "Monitors",
        "Base Price": 320,
        "Base Cost Ratio": 0.74,
        "Discount Sensitivity": 1.22,
        "Demand Weight": 1.00,
        "Quantity Base": 2.0,
        "Return Bias": 0.012,
    },
    {
        "Product ID": "P004",
        "Product Name": "VisionView 27 QHD",
        "Category": "Technology",
        "Sub-Category": "Monitors",
        "Base Price": 480,
        "Base Cost Ratio": 0.75,
        "Discount Sensitivity": 1.25,
        "Demand Weight": 0.86,
        "Quantity Base": 1.8,
        "Return Bias": 0.013,
    },
    {
        "Product ID": "P005",
        "Product Name": "LaserJet Office X1",
        "Category": "Technology",
        "Sub-Category": "Printers",
        "Base Price": 410,
        "Base Cost Ratio": 0.82,
        "Discount Sensitivity": 1.32,
        "Demand Weight": 0.78,
        "Quantity Base": 1.5,
        "Return Bias": 0.015,
    },
    {
        "Product ID": "P006",
        "Product Name": "InkFlow Compact",
        "Category": "Technology",
        "Sub-Category": "Printers",
        "Base Price": 230,
        "Base Cost Ratio": 0.84,
        "Discount Sensitivity": 1.30,
        "Demand Weight": 0.82,
        "Quantity Base": 1.7,
        "Return Bias": 0.016,
    },
    {
        "Product ID": "P007",
        "Product Name": "DockPro Station",
        "Category": "Technology",
        "Sub-Category": "Accessories",
        "Base Price": 145,
        "Base Cost Ratio": 0.63,
        "Discount Sensitivity": 0.92,
        "Demand Weight": 1.06,
        "Quantity Base": 2.8,
        "Return Bias": 0.006,
    },
    {
        "Product ID": "P008",
        "Product Name": "FlexMouse Wireless",
        "Category": "Technology",
        "Sub-Category": "Accessories",
        "Base Price": 38,
        "Base Cost Ratio": 0.55,
        "Discount Sensitivity": 0.88,
        "Demand Weight": 1.16,
        "Quantity Base": 4.2,
        "Return Bias": 0.004,
    },
    {
        "Product ID": "P009",
        "Product Name": "TypeEdge Keyboard",
        "Category": "Technology",
        "Sub-Category": "Accessories",
        "Base Price": 72,
        "Base Cost Ratio": 0.57,
        "Discount Sensitivity": 0.90,
        "Demand Weight": 1.08,
        "Quantity Base": 3.5,
        "Return Bias": 0.005,
    },
    {
        "Product ID": "P010",
        "Product Name": "FocusCam Pro",
        "Category": "Technology",
        "Sub-Category": "Accessories",
        "Base Price": 96,
        "Base Cost Ratio": 0.59,
        "Discount Sensitivity": 0.95,
        "Demand Weight": 0.92,
        "Quantity Base": 2.6,
        "Return Bias": 0.006,
    },
    {
        "Product ID": "P011",
        "Product Name": "ErgoSeat Mesh",
        "Category": "Furniture",
        "Sub-Category": "Chairs",
        "Base Price": 285,
        "Base Cost Ratio": 0.66,
        "Discount Sensitivity": 1.08,
        "Demand Weight": 0.94,
        "Quantity Base": 1.9,
        "Return Bias": 0.009,
    },
    {
        "Product ID": "P012",
        "Product Name": "TaskSeat Essential",
        "Category": "Furniture",
        "Sub-Category": "Chairs",
        "Base Price": 175,
        "Base Cost Ratio": 0.65,
        "Discount Sensitivity": 1.05,
        "Demand Weight": 1.02,
        "Quantity Base": 2.2,
        "Return Bias": 0.008,
    },
    {
        "Product ID": "P013",
        "Product Name": "LiftDesk 120",
        "Category": "Furniture",
        "Sub-Category": "Desks",
        "Base Price": 620,
        "Base Cost Ratio": 0.73,
        "Discount Sensitivity": 1.16,
        "Demand Weight": 0.72,
        "Quantity Base": 1.3,
        "Return Bias": 0.007,
    },
    {
        "Product ID": "P014",
        "Product Name": "WorkBench 160",
        "Category": "Furniture",
        "Sub-Category": "Desks",
        "Base Price": 790,
        "Base Cost Ratio": 0.76,
        "Discount Sensitivity": 1.20,
        "Demand Weight": 0.58,
        "Quantity Base": 1.2,
        "Return Bias": 0.008,
    },
    {
        "Product ID": "P015",
        "Product Name": "SteelStore Cabinet",
        "Category": "Furniture",
        "Sub-Category": "Storage",
        "Base Price": 350,
        "Base Cost Ratio": 0.67,
        "Discount Sensitivity": 1.02,
        "Demand Weight": 0.82,
        "Quantity Base": 1.6,
        "Return Bias": 0.005,
    },
    {
        "Product ID": "P016",
        "Product Name": "ModShelf Plus",
        "Category": "Furniture",
        "Sub-Category": "Storage",
        "Base Price": 220,
        "Base Cost Ratio": 0.64,
        "Discount Sensitivity": 0.96,
        "Demand Weight": 0.86,
        "Quantity Base": 2.0,
        "Return Bias": 0.005,
    },
    {
        "Product ID": "P017",
        "Product Name": "Forum Meeting Table",
        "Category": "Furniture",
        "Sub-Category": "Tables",
        "Base Price": 980,
        "Base Cost Ratio": 0.83,
        "Discount Sensitivity": 1.28,
        "Demand Weight": 0.48,
        "Quantity Base": 1.1,
        "Return Bias": 0.006,
    },
    {
        "Product ID": "P018",
        "Product Name": "Compact Side Table",
        "Category": "Furniture",
        "Sub-Category": "Tables",
        "Base Price": 125,
        "Base Cost Ratio": 0.74,
        "Discount Sensitivity": 1.12,
        "Demand Weight": 0.70,
        "Quantity Base": 1.8,
        "Return Bias": 0.006,
    },
    {
        "Product ID": "P019",
        "Product Name": "Premium Paper Pack",
        "Category": "Office Supplies",
        "Sub-Category": "Paper",
        "Base Price": 19,
        "Base Cost Ratio": 0.71,
        "Discount Sensitivity": 0.84,
        "Demand Weight": 1.20,
        "Quantity Base": 7.5,
        "Return Bias": 0.002,
    },
    {
        "Product ID": "P020",
        "Product Name": "Eco Paper Pack",
        "Category": "Office Supplies",
        "Sub-Category": "Paper",
        "Base Price": 14,
        "Base Cost Ratio": 0.72,
        "Discount Sensitivity": 0.88,
        "Demand Weight": 1.10,
        "Quantity Base": 8.2,
        "Return Bias": 0.002,
    },
    {
        "Product ID": "P021",
        "Product Name": "Exec Binder Set",
        "Category": "Office Supplies",
        "Sub-Category": "Binders",
        "Base Price": 28,
        "Base Cost Ratio": 0.56,
        "Discount Sensitivity": 0.78,
        "Demand Weight": 0.98,
        "Quantity Base": 5.8,
        "Return Bias": 0.002,
    },
    {
        "Product ID": "P022",
        "Product Name": "Economy Binder Set",
        "Category": "Office Supplies",
        "Sub-Category": "Binders",
        "Base Price": 18,
        "Base Cost Ratio": 0.54,
        "Discount Sensitivity": 0.76,
        "Demand Weight": 1.02,
        "Quantity Base": 6.1,
        "Return Bias": 0.002,
    },
    {
        "Product ID": "P023",
        "Product Name": "Gel Pen Box",
        "Category": "Office Supplies",
        "Sub-Category": "Writing",
        "Base Price": 12,
        "Base Cost Ratio": 0.49,
        "Discount Sensitivity": 0.72,
        "Demand Weight": 1.05,
        "Quantity Base": 7.0,
        "Return Bias": 0.001,
    },
    {
        "Product ID": "P024",
        "Product Name": "Marker Kit",
        "Category": "Office Supplies",
        "Sub-Category": "Writing",
        "Base Price": 15,
        "Base Cost Ratio": 0.50,
        "Discount Sensitivity": 0.74,
        "Demand Weight": 0.96,
        "Quantity Base": 6.4,
        "Return Bias": 0.001,
    },
    {
        "Product ID": "P025",
        "Product Name": "Shipping Labels",
        "Category": "Office Supplies",
        "Sub-Category": "Labels",
        "Base Price": 11,
        "Base Cost Ratio": 0.46,
        "Discount Sensitivity": 0.70,
        "Demand Weight": 0.92,
        "Quantity Base": 7.6,
        "Return Bias": 0.001,
    },
    {
        "Product ID": "P026",
        "Product Name": "Shelf Labels",
        "Category": "Office Supplies",
        "Sub-Category": "Labels",
        "Base Price": 9,
        "Base Cost Ratio": 0.45,
        "Discount Sensitivity": 0.68,
        "Demand Weight": 0.88,
        "Quantity Base": 8.0,
        "Return Bias": 0.001,
    },
    {
        "Product ID": "P027",
        "Product Name": "Archive Box",
        "Category": "Office Supplies",
        "Sub-Category": "Filing",
        "Base Price": 22,
        "Base Cost Ratio": 0.58,
        "Discount Sensitivity": 0.82,
        "Demand Weight": 0.84,
        "Quantity Base": 4.9,
        "Return Bias": 0.002,
    },
    {
        "Product ID": "P028",
        "Product Name": "Folder Kit",
        "Category": "Office Supplies",
        "Sub-Category": "Filing",
        "Base Price": 16,
        "Base Cost Ratio": 0.55,
        "Discount Sensitivity": 0.80,
        "Demand Weight": 0.90,
        "Quantity Base": 5.7,
        "Return Bias": 0.002,
    },
]

SALES_REPS = [
    {"Sales Rep": "Ana Costa", "Home Region": "Southeast"},
    {"Sales Rep": "Bruno Almeida", "Home Region": "Southeast"},
    {"Sales Rep": "Carla Nogueira", "Home Region": "South"},
    {"Sales Rep": "Daniel Rocha", "Home Region": "South"},
    {"Sales Rep": "Eduarda Lima", "Home Region": "Northeast"},
    {"Sales Rep": "Felipe Santos", "Home Region": "Northeast"},
    {"Sales Rep": "Gabriela Moura", "Home Region": "Midwest"},
    {"Sales Rep": "Henrique Souza", "Home Region": "Midwest"},
    {"Sales Rep": "Isabela Duarte", "Home Region": "North"},
    {"Sales Rep": "Joao Pires", "Home Region": "North"},
    {"Sales Rep": "Larissa Araujo", "Home Region": "Southeast"},
    {"Sales Rep": "Mateus Ribeiro", "Home Region": "South"},
]

COMPANY_PREFIXES = [
    "Aurora",
    "Prime",
    "Vertex",
    "Atlas",
    "Nova",
    "Summit",
    "Harbor",
    "BlueWave",
    "Capital",
    "Union",
    "Golden",
    "Lighthouse",
    "TrueNorth",
    "Core",
    "Pioneer",
    "Sterling",
]

COMPANY_NOUNS = [
    "Retail",
    "Distribution",
    "Trading",
    "Services",
    "Supply",
    "Solutions",
    "Office",
    "Markets",
    "Business",
    "Commerce",
    "Logistics",
    "Group",
]

LAST_NAMES = [
    "Silva",
    "Santos",
    "Oliveira",
    "Souza",
    "Lima",
    "Pereira",
    "Costa",
    "Almeida",
    "Gomes",
    "Ribeiro",
    "Martins",
    "Carvalho",
    "Araujo",
    "Fernandes",
    "Rocha",
]

FIRST_NAMES = [
    "Alice",
    "Beatriz",
    "Caio",
    "Daniel",
    "Eduardo",
    "Fernanda",
    "Giovana",
    "Helena",
    "Igor",
    "Julia",
    "Karen",
    "Lucas",
    "Marina",
    "Nicolas",
    "Patricia",
    "Rafael",
    "Sofia",
    "Thiago",
    "Vanessa",
    "Yasmin",
]


def ensure_directories() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
